language: node_js

node_js:
  - 6
  - 7
  - stable

before_script:
  - "npm install"

script:
  - "npm test"

after_success:
  - "./node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
  - npm run semantic-release

notifications:
  email:
    - cjrodr@yahoo.com
